# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install wheel
    python setup.py bdist_wheel
    pip install pytest
    pip install --upgrade --force-reinstall dist/asset_behave_api-1.1.0-py3-none-any.whl
    
  displayName: 'Install dependencies'

- script: |
    cd /opt/hostedtoolcache/Python/
    asset_behave_api
    pytest --junitxml= '*/reports/TESTS-*.xml'
    ls
  
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '*/reports/TESTS-*.xml'
    #testResultsFiles: '/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/app_b/features/reports/TESTS-*.xml'
  condition: succeededOrFailed()